/* ========================================
   tpl/presets.tpl.js — Preset-specific file templates
   (WordPress, Laravel, Symfony, Next.js, Nest.js, Angular, Django, Flask, Spring Boot)
   ======================================== */

Object.assign(Templates, {

  // ---- WordPress wp-config.php ----
  wpConfig(config) {
    const dbHost = config.mysql ? 'mysql' : 'mariadb';
    const dbEnvPrefix = config.mysql ? 'MYSQL' : 'MARIADB';
    return `<?php
/**
 * WordPress configuration — generated by Docker Stack Generator
 */

// Database settings
define( 'DB_NAME',     getenv('${dbEnvPrefix}_DATABASE') ?: '${config.projectName.replace(/-/g, '_')}' );
define( 'DB_USER',     getenv('${dbEnvPrefix}_USER') ?: 'appuser' );
define( 'DB_PASSWORD', getenv('${dbEnvPrefix}_PASSWORD') );
define( 'DB_HOST',     '${dbHost}' );
define( 'DB_CHARSET',  'utf8mb4' );
define( 'DB_COLLATE',  '' );

// Authentication unique keys and salts
// SECURITY: Generate new keys at: https://api.wordpress.org/secret-key/1.1/salt/
define( 'AUTH_KEY',         '${this.generateSecurePassword(64)}' );
define( 'SECURE_AUTH_KEY',  '${this.generateSecurePassword(64)}' );
define( 'LOGGED_IN_KEY',    '${this.generateSecurePassword(64)}' );
define( 'NONCE_KEY',        '${this.generateSecurePassword(64)}' );
define( 'AUTH_SALT',        '${this.generateSecurePassword(64)}' );
define( 'SECURE_AUTH_SALT', '${this.generateSecurePassword(64)}' );
define( 'LOGGED_IN_SALT',   '${this.generateSecurePassword(64)}' );
define( 'NONCE_SALT',       '${this.generateSecurePassword(64)}' );

$table_prefix = 'wp_';

// Site URL
define( 'WP_HOME',    '${config.ssl !== 'none' ? 'https' : 'http'}://${config.domain || 'localhost'}' );
define( 'WP_SITEURL', '${config.ssl !== 'none' ? 'https' : 'http'}://${config.domain || 'localhost'}' );

// Debug
define( 'WP_DEBUG',     true );
define( 'WP_DEBUG_LOG', true );

// SMTP via Mailpit
${config.mailpit ? "define( 'WPMS_ON',                true );\ndefine( 'WPMS_SMTP_HOST',        'mailpit' );\ndefine( 'WPMS_SMTP_PORT',        1025 );\ndefine( 'WPMS_SSL',              '' );\ndefine( 'WPMS_SMTP_AUTH',        false );" : '// Enable Mailpit in tools section for email testing'}

// Filesystem
define( 'FS_METHOD', 'direct' );

// Memory
define( 'WP_MEMORY_LIMIT', '256M' );

/** Absolute path to the WordPress directory. */
if ( ! defined( 'ABSPATH' ) ) {
    define( 'ABSPATH', __DIR__ . '/' );
}

require_once ABSPATH . 'wp-settings.php';
`;
  },

  // ---- Laravel .env ----
  laravelEnv(config) {
    let dbConnection = 'mysql';
    let dbHost = 'mysql';
    let dbPort = '3306';
    let dbDatabase = config.projectName.replace(/-/g, '_');
    const dbUser = 'appuser';
    let dbPass;
    if (config.postgres) {
      dbConnection = 'pgsql'; dbHost = 'postgres'; dbPort = '5432';
      dbPass = this.getPassword('postgres_user');
    } else if (config.mariadb) {
      dbConnection = 'mariadb'; dbHost = 'mariadb';
      dbPass = this.getPassword('mariadb_user');
    } else {
      dbPass = this.getPassword('mysql_user');
    }

    const starter = config.laravelStarter || 'none';
    const hasFrontend = starter !== 'none';

    const appKeyRaw = this.generateSecurePassword(32);
    const appKeyBase64 = btoa(appKeyRaw);

    return `APP_NAME="${config.projectName}"
APP_ENV=local
APP_KEY=base64:${appKeyBase64}
APP_DEBUG=true
APP_TIMEZONE=UTC
APP_URL=${config.ssl !== 'none' ? 'https' : 'http'}://${config.domain || 'localhost'}

APP_LOCALE=en
APP_FALLBACK_LOCALE=en
APP_FAKER_LOCALE=en_US

APP_MAINTENANCE_DRIVER=file

LOG_CHANNEL=stack
LOG_STACK=single
LOG_DEPRECATIONS_CHANNEL=null
LOG_LEVEL=debug

DB_CONNECTION=${dbConnection}
DB_HOST=${dbHost}
DB_PORT=${dbPort}
DB_DATABASE=${dbDatabase}
DB_USERNAME=${dbUser}
DB_PASSWORD=${dbPass}

SESSION_DRIVER=redis
SESSION_LIFETIME=120

BROADCAST_CONNECTION=log
FILESYSTEM_DISK=local
QUEUE_CONNECTION=redis

CACHE_STORE=redis
CACHE_PREFIX=${config.projectName.replace(/-/g, '_')}_cache

REDIS_HOST=redis
REDIS_PASSWORD=${this.getPassword('redis')}
REDIS_PORT=6379

MAIL_MAILER=smtp
MAIL_HOST=${config.mailpit ? 'mailpit' : '127.0.0.1'}
MAIL_PORT=${config.mailpit ? '1025' : '2525'}
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_ENCRYPTION=null
MAIL_FROM_ADDRESS="hello@${config.domain || 'example.com'}"
MAIL_FROM_NAME="\${APP_NAME}"

${config.minio ? `AWS_ACCESS_KEY_ID=minioadmin
AWS_SECRET_ACCESS_KEY=${this.getPassword('minio')}
AWS_DEFAULT_REGION=us-east-1
AWS_BUCKET=${config.projectName.replace(/-/g, '-')}-bucket
AWS_ENDPOINT=http://minio:9000
AWS_USE_PATH_STYLE_ENDPOINT=true` : ''}

${hasFrontend ? `VITE_APP_NAME="\${APP_NAME}"` : ''}
`;
  },

  // ---- Symfony .env ----
  symfonyEnv(config) {
    let dbUrl = '';
    if (config.postgres) {
      dbUrl = `postgresql://appuser:apppassword@postgres:5432/${config.projectName.replace(/-/g, '_')}?serverVersion=${config.postgresVersion}&charset=utf8`;
    } else if (config.mariadb) {
      dbUrl = `mysql://appuser:apppassword@mariadb:3306/${config.projectName.replace(/-/g, '_')}?serverVersion=mariadb-${config.mariadbVersion}`;
    } else {
      dbUrl = `mysql://appuser:apppassword@mysql:3306/${config.projectName.replace(/-/g, '_')}?serverVersion=${config.mysqlVersion}`;
    }

    return `# Symfony ${config.symfonyVersion || '7.2'} — generated by Docker Stack Generator

APP_ENV=dev
APP_SECRET=CHANGE_ME_WITH_A_RANDOM_SECRET
APP_DEBUG=1

# Database
DATABASE_URL="${dbUrl}"

# Messenger (async)
MESSENGER_TRANSPORT_DSN=${config.redis ? 'redis://redis:6379/messages' : 'doctrine://default?auto_setup=0'}

${config.redis ? '# Redis\nREDIS_URL=redis://redis:6379' : ''}

# Mailer
MAILER_DSN=${config.mailpit ? 'smtp://mailpit:1025' : 'null://null'}

# CORS
CORS_ALLOW_ORIGIN='^https?://(localhost|127\\.0\\.0\\.1)(:[0-9]+)?$'
`;
  },

  // ---- Next.js .env.local ----
  nextjsEnvLocal(config) {
    let env = `# Next.js — generated by Docker Stack Generator\n\n`;
    env += `NEXT_PUBLIC_APP_NAME="${config.projectName}"\n`;
    env += `NEXT_PUBLIC_APP_URL=${config.ssl !== 'none' ? 'https' : 'http'}://${config.domain || 'localhost:3000'}\n\n`;

    if (config.postgres) {
      env += `DATABASE_URL="postgresql://appuser:apppassword@postgres:5432/${config.projectName.replace(/-/g, '_')}"\n`;
    } else if (config.mysql) {
      env += `DATABASE_URL="mysql://appuser:apppassword@mysql:3306/${config.projectName.replace(/-/g, '_')}"\n`;
    } else if (config.mongo) {
      env += `MONGODB_URI="mongodb://admin:adminpassword@mongo:27017/${config.projectName.replace(/-/g, '_')}?authSource=admin"\n`;
    }

    if (config.redis) env += `REDIS_URL="redis://redis:6379"\n`;

    env += `\n# Auth (NextAuth.js)\nNEXTAUTH_URL=${config.ssl !== 'none' ? 'https' : 'http'}://${config.domain || 'localhost:3000'}\nNEXTAUTH_SECRET=CHANGE_ME_GENERATE_WITH_OPENSSL\n`;
    return env;
  },

  // ---- Nest.js .env ----
  nestjsEnv(config) {
    const orm = config.nestjsOrm || 'typeorm';
    let env = `# NestJS — generated by Docker Stack Generator\n\n`;
    env += `NODE_ENV=development\nPORT=3000\n\n`;

    if (config.postgres && orm !== 'mongoose') {
      env += `# Database (PostgreSQL)\nDB_TYPE=postgres\nDB_HOST=postgres\nDB_PORT=5432\nDB_USERNAME=appuser\nDB_PASSWORD=apppassword\nDB_DATABASE=${config.projectName.replace(/-/g, '_')}\nDB_SYNCHRONIZE=true\n\n`;
    } else if (config.mysql && orm !== 'mongoose') {
      env += `# Database (MySQL)\nDB_TYPE=mysql\nDB_HOST=mysql\nDB_PORT=3306\nDB_USERNAME=appuser\nDB_PASSWORD=apppassword\nDB_DATABASE=${config.projectName.replace(/-/g, '_')}\nDB_SYNCHRONIZE=true\n\n`;
    } else if (config.mongo) {
      env += `# MongoDB\nMONGODB_URI=mongodb://admin:adminpassword@mongo:27017/${config.projectName.replace(/-/g, '_')}?authSource=admin\n\n`;
    }

    if (config.redis) env += `# Redis\nREDIS_HOST=redis\nREDIS_PORT=6379\n\n`;
    env += `# JWT\nJWT_SECRET=CHANGE_ME\nJWT_EXPIRES_IN=3600s\n`;
    return env;
  },

  // ---- Django .env ----
  djangoEnv(config) {
    let dbUrl = '';
    if (config.postgres) {
      dbUrl = `postgres://appuser:apppassword@postgres:5432/${config.projectName.replace(/-/g, '_')}`;
    } else if (config.mysql || config.mariadb) {
      const host = config.mysql ? 'mysql' : 'mariadb';
      dbUrl = `mysql://appuser:apppassword@${host}:3306/${config.projectName.replace(/-/g, '_')}`;
    }

    return `# Django ${config.djangoVersion || '5.1'} — generated by Docker Stack Generator

DEBUG=True
SECRET_KEY=change-me-to-a-long-random-string
ALLOWED_HOSTS=localhost,127.0.0.1,${config.domain || ''}

# Database
DATABASE_URL=${dbUrl}

${config.redis ? '# Redis / Cache\nREDIS_URL=redis://redis:6379/0\nCACHE_URL=redis://redis:6379/1' : ''}

# Email
${config.mailpit ? 'EMAIL_BACKEND=django.core.mail.backends.smtp.EmailBackend\nEMAIL_HOST=mailpit\nEMAIL_PORT=1025' : 'EMAIL_BACKEND=django.core.mail.backends.console.EmailBackend'}

# Static & Media
STATIC_URL=/static/
MEDIA_URL=/media/

${config.minio ? `# MinIO / S3\nAWS_ACCESS_KEY_ID=minioadmin\nAWS_SECRET_ACCESS_KEY=minioadmin\nAWS_STORAGE_BUCKET_NAME=${config.projectName}-media\nAWS_S3_ENDPOINT_URL=http://minio:9000` : ''}
`;
  },

  djangoRequirements(config) {
    let reqs = `Django>=${config.djangoVersion || '5.1'},<${parseFloat(config.djangoVersion || '5.1') + 0.1}\ngunicorn>=21.2.0\n`;
    if (config.postgres) reqs += `psycopg2-binary>=2.9\n`;
    if (config.mysql || config.mariadb) reqs += `mysqlclient>=2.2\n`;
    if (config.redis) reqs += `django-redis>=5.4\nredis>=5.0\n`;
    reqs += `dj-database-url>=2.1\npython-decouple>=3.8\nwhitenoise>=6.5\n`;
    if (config.minio) reqs += `django-storages>=1.14\nboto3>=1.34\n`;
    return reqs;
  },

  // ---- Flask .env ----
  flaskEnv(config) {
    let env = `# Flask — generated by Docker Stack Generator\n\n`;
    env += `FLASK_APP=app\nFLASK_ENV=development\nFLASK_DEBUG=1\nSECRET_KEY=change-me\n\n`;

    if (config.postgres) {
      env += `DATABASE_URL=postgresql://appuser:apppassword@postgres:5432/${config.projectName.replace(/-/g, '_')}\n`;
    } else if (config.mysql || config.mariadb) {
      const host = config.mysql ? 'mysql' : 'mariadb';
      env += `DATABASE_URL=mysql+pymysql://appuser:apppassword@${host}:3306/${config.projectName.replace(/-/g, '_')}\n`;
    } else if (config.mongo) {
      env += `MONGODB_URI=mongodb://admin:adminpassword@mongo:27017/${config.projectName.replace(/-/g, '_')}?authSource=admin\n`;
    }

    if (config.redis) env += `REDIS_URL=redis://redis:6379/0\n`;
    if (config.mailpit) env += `\nMAIL_SERVER=mailpit\nMAIL_PORT=1025\nMAIL_USE_TLS=False\n`;
    return env;
  },

  flaskRequirements(config) {
    let reqs = `Flask>=3.0\npython-dotenv>=1.0\n`;
    if (config.postgres) reqs += `Flask-SQLAlchemy>=3.1\npsycopg2-binary>=2.9\n`;
    if (config.mysql || config.mariadb) reqs += `Flask-SQLAlchemy>=3.1\nPyMySQL>=1.1\n`;
    if (config.mongo) reqs += `Flask-PyMongo>=2.3\n`;
    if (config.redis) reqs += `Flask-Caching>=2.1\nredis>=5.0\n`;
    if (config.mailpit) reqs += `Flask-Mail>=0.9\n`;
    return reqs;
  },

  // ---- Spring Boot ----
  springProperties(config) {
    let props = `# Spring Boot — generated by Docker Stack Generator\n\nspring.application.name=${config.projectName}\nserver.port=8080\n\n`;

    if (config.postgres) {
      props += `# PostgreSQL\nspring.datasource.url=jdbc:postgresql://postgres:5432/${config.projectName.replace(/-/g, '_')}\nspring.datasource.username=appuser\nspring.datasource.password=apppassword\nspring.datasource.driver-class-name=org.postgresql.Driver\nspring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect\n`;
    } else if (config.mysql || config.mariadb) {
      const host = config.mysql ? 'mysql' : 'mariadb';
      const driver = config.mariadb ? 'org.mariadb.jdbc.Driver' : 'com.mysql.cj.jdbc.Driver';
      const dialect = config.mariadb ? 'org.hibernate.dialect.MariaDBDialect' : 'org.hibernate.dialect.MySQLDialect';
      props += `# ${config.mariadb ? 'MariaDB' : 'MySQL'}\nspring.datasource.url=jdbc:mysql://${host}:3306/${config.projectName.replace(/-/g, '_')}\nspring.datasource.username=appuser\nspring.datasource.password=apppassword\nspring.datasource.driver-class-name=${driver}\nspring.jpa.database-platform=${dialect}\n`;
    } else if (config.mongo) {
      props += `# MongoDB\nspring.data.mongodb.uri=mongodb://admin:adminpassword@mongo:27017/${config.projectName.replace(/-/g, '_')}?authSource=admin\n`;
    }

    props += `\nspring.jpa.hibernate.ddl-auto=update\nspring.jpa.show-sql=true\n`;

    if (config.redis) {
      props += `\n# Redis\nspring.data.redis.host=redis\nspring.data.redis.port=6379\n`;
    }

    if (config.mailpit) {
      props += `\n# Mail (Mailpit)\nspring.mail.host=mailpit\nspring.mail.port=1025\nspring.mail.properties.mail.smtp.auth=false\nspring.mail.properties.mail.smtp.starttls.enable=false\n`;
    }

    return props;
  },

  springPomXml(config) {
    const deps = [];
    deps.push(`        <dependency>\n            <groupId>org.springframework.boot</groupId>\n            <artifactId>spring-boot-starter-web</artifactId>\n        </dependency>`);

    if (config.postgres || config.mysql || config.mariadb) {
      deps.push(`        <dependency>\n            <groupId>org.springframework.boot</groupId>\n            <artifactId>spring-boot-starter-data-jpa</artifactId>\n        </dependency>`);
    }
    if (config.postgres) {
      deps.push(`        <dependency>\n            <groupId>org.postgresql</groupId>\n            <artifactId>postgresql</artifactId>\n            <scope>runtime</scope>\n        </dependency>`);
    }
    if (config.mysql) {
      deps.push(`        <dependency>\n            <groupId>com.mysql</groupId>\n            <artifactId>mysql-connector-j</artifactId>\n            <scope>runtime</scope>\n        </dependency>`);
    }
    if (config.mariadb) {
      deps.push(`        <dependency>\n            <groupId>org.mariadb.jdbc</groupId>\n            <artifactId>mariadb-java-client</artifactId>\n            <scope>runtime</scope>\n        </dependency>`);
    }
    if (config.mongo) {
      deps.push(`        <dependency>\n            <groupId>org.springframework.boot</groupId>\n            <artifactId>spring-boot-starter-data-mongodb</artifactId>\n        </dependency>`);
    }
    if (config.redis) {
      deps.push(`        <dependency>\n            <groupId>org.springframework.boot</groupId>\n            <artifactId>spring-boot-starter-data-redis</artifactId>\n        </dependency>`);
    }
    if (config.mailpit) {
      deps.push(`        <dependency>\n            <groupId>org.springframework.boot</groupId>\n            <artifactId>spring-boot-starter-mail</artifactId>\n        </dependency>`);
    }
    deps.push(`        <dependency>\n            <groupId>org.springframework.boot</groupId>\n            <artifactId>spring-boot-starter-test</artifactId>\n            <scope>test</scope>\n        </dependency>`);

    return `<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>3.3.0</version>
    </parent>
    <groupId>com.example</groupId>
    <artifactId>${this.escapeXml(config.projectName)}</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <name>${this.escapeXml(config.projectName)}</name>
    <properties>
        <java.version>${config.javaVersionVal || '21'}</java.version>
    </properties>
    <dependencies>
${deps.join('\n')}
    </dependencies>
    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
        </plugins>
    </build>
</project>
`;
  },

  // ---- Angular ----
  angularEnvironment(config) {
    return `export const environment = {
  production: false,
  appName: '${config.projectName}',
  apiUrl: '${config.ssl !== 'none' ? 'https' : 'http'}://${config.domain || 'localhost'}/api'
};
`;
  }
});
