/* ========================================
   tpl/readme.js — README.md template
   ======================================== */

Object.assign(Templates, {

  readme(config) {
    const runtimeName = config.runtime === 'docker' ? 'Docker' : 'Podman';
    const composeCmd = this.getComposeCmd(config);

    let md = `# ${config.projectName}\n\nStack ${runtimeName} generated by **Container Stack Generator**.\n\n`;
    md += `**Runtime:** ${runtimeName}\n\n`;

    if (config.preset && config.preset !== 'none') {
      const presetNames = {
        wordpress: 'WordPress', laravel: 'Laravel', symfony: 'Symfony',
        nextjs: 'Next.js', nestjs: 'NestJS', angular: 'Angular',
        django: 'Django', flask: 'Flask', springboot: 'Spring Boot'
      };
      md += `**Preset:** ${presetNames[config.preset] || config.preset}\n\n`;
    }

    md += `## Services\n\n`;
    const services = [];
    if (config.webserver !== 'none') services.push(`- **${config.webserver.charAt(0).toUpperCase() + config.webserver.slice(1)}** (web server)`);
    if (config.php) services.push(`- **PHP-FPM ${config.phpVersion}**`);
    if (config.node) services.push(`- **Node.js ${config.nodeVersion === 'nvm' ? '(NVM)' : config.nodeVersion}**`);
    if (config.python) services.push(`- **Python ${config.pythonVersionVal || '3.12'}**`);
    if (config.java) services.push(`- **Java ${config.javaVersionVal || '21'}** (Spring Boot)`);
    if (config.mysql) services.push(`- **MySQL ${config.mysqlVersion}**`);
    if (config.mariadb) services.push(`- **MariaDB ${config.mariadbVersion}**`);
    if (config.postgres) services.push(`- **PostgreSQL ${config.postgresVersion}**`);
    if (config.mongo) services.push(`- **MongoDB ${config.mongoVersion}**`);
    if (config.redis) services.push('- **Redis 7**');
    if (config.memcached) services.push('- **Memcached**');
    if (config.rabbitmq) services.push('- **RabbitMQ**');
    if (config.adminer) services.push('- **Adminer** (:8081)');
    if (config.phpmyadmin) services.push('- **phpMyAdmin** (:8082)');
    if (config.pgadmin) services.push('- **pgAdmin** (:8083)');
    if (config.mongoexpress) services.push('- **Mongo Express** (:8084)');
    if (config.mailpit) services.push('- **Mailpit** (SMTP :1025, UI :8025)');
    if (config.minio) services.push('- **MinIO** (API :9000, Console :9001)');
    if (config.elasticsearch) services.push('- **Elasticsearch 8** (:9200)');
    md += services.join('\n') + '\n';

    md += `\n## Environnement de développement\n\n`;

    const envDocs = {
      'windows-laragon': { name: 'Windows + Laragon', desc: 'Le SSL est géré automatiquement par Laragon. Les containers Podman n\'ont pas besoin de certificats SSL.', scriptType: 'powershell', url: `https://${config.projectName}.test`, note: 'Le certificat SSL est généré automatiquement par Laragon' },
      'windows-herd': { name: 'Windows + Herd', desc: 'Le SSL est géré automatiquement par Herd. Les containers Podman n\'ont pas besoin de certificats SSL.', scriptType: 'powershell', url: `https://${config.projectName}.test`, note: 'Le certificat SSL est généré automatiquement par Herd' },
      'windows-xampp': { name: 'Windows + XAMPP', desc: 'Configurez Apache/Nginx de XAMPP pour faire proxy vers les containers Podman.', scriptType: 'powershell', url: `http://localhost/${config.projectName}`, note: 'Configurez un VirtualHost dans httpd-vhosts.conf pour le SSL', extraSetup: `\n### Configuration XAMPP\n\n1. Éditez \`C:\\xampp\\apache\\conf\\extra\\httpd-vhosts.conf\`:\n\`\`\`apache\n<VirtualHost *:80>\n    ServerName ${config.projectName}.local\n    ProxyPreserveHost On\n    ProxyPass / http://localhost:80/\n    ProxyPassReverse / http://localhost:80/\n</VirtualHost>\n\`\`\`\n\n2. Redémarrez Apache depuis le panneau XAMPP\n` },
      'windows-wamp': { name: 'Windows + WAMP', desc: 'Configurez Apache de WAMP pour faire proxy vers les containers Podman.', scriptType: 'powershell', url: `http://localhost/${config.projectName}`, note: 'Configurez un VirtualHost dans httpd-vhosts.conf pour le SSL', extraSetup: `\n### Configuration WAMP\n\n1. Éditez \`C:\\wamp64\\bin\\apache\\apache2.x.x\\conf\\extra\\httpd-vhosts.conf\`:\n\`\`\`apache\n<VirtualHost *:80>\n    ServerName ${config.projectName}.local\n    ProxyPreserveHost On\n    ProxyPass / http://localhost:80/\n    ProxyPassReverse / http://localhost:80/\n</VirtualHost>\n\`\`\`\n\n2. Redémarrez Apache depuis l'icône WAMP\n` },
      'mac-mamp': { name: 'macOS + MAMP', desc: 'Configurez Apache/Nginx de MAMP pour faire proxy vers les containers Podman.', scriptType: 'bash', url: `http://localhost:8888/${config.projectName}`, note: 'Par défaut MAMP écoute sur le port 8888', extraSetup: `\n### Configuration MAMP\n\n1. Éditez \`/Applications/MAMP/conf/apache/httpd.conf\`:\n\`\`\`apache\n<VirtualHost *:8888>\n    ServerName ${config.projectName}.local\n    ProxyPreserveHost On\n    ProxyPass / http://localhost:80/\n    ProxyPassReverse / http://localhost:80/\n</VirtualHost>\n\`\`\`\n\n2. Redémarrez les serveurs MAMP\n` },
      'linux-lamp': { name: 'Linux + LAMP', desc: 'Configurez Apache/Nginx du système pour faire proxy vers les containers Podman.', scriptType: 'bash', url: `http://localhost/${config.projectName}`, note: 'Configurez un VirtualHost Apache/Nginx pour le SSL', extraSetup: `\n### Configuration LAMP (Apache)\n\n1. Créez \`/etc/apache2/sites-available/${config.projectName}.conf\`:\n\`\`\`apache\n<VirtualHost *:80>\n    ServerName ${config.projectName}.local\n    ProxyPreserveHost On\n    ProxyPass / http://localhost:80/\n    ProxyPassReverse / http://localhost:80/\n</VirtualHost>\n\`\`\`\n\n2. Activez le site:\n\`\`\`bash\nsudo a2ensite ${config.projectName}\nsudo systemctl reload apache2\n\`\`\`\n` },
      'linux-local': { name: 'Linux standalone', desc: 'Le SSL est géré directement par les containers Podman.', scriptType: 'bash', url: config.ssl !== 'none' ? `https://${config.domain || 'localhost'}` : `http://${config.domain || 'localhost'}`, note: config.ssl === 'mkcert' ? 'SSL via mkcert' : config.ssl === 'letsencrypt' ? 'SSL via Let\'s Encrypt' : '', sslSetup: config.ssl === 'mkcert' ? `\n### Configuration SSL (mkcert)\n\nLe script de démarrage génère automatiquement les certificats SSL via mkcert.\n\nSi vous devez le faire manuellement:\n\`\`\`bash\nmkcert -install\ncd certs\nmkcert ${config.domain || 'localhost'}\ncd ..\n\`\`\`\n` : '' },
      'mac-local': { name: 'macOS standalone', desc: 'Le SSL est géré directement par les containers Podman.', scriptType: 'bash', url: config.ssl !== 'none' ? `https://${config.domain || 'localhost'}` : `http://${config.domain || 'localhost'}`, note: config.ssl === 'mkcert' ? 'SSL via mkcert' : config.ssl === 'letsencrypt' ? 'SSL via Let\'s Encrypt' : '', sslSetup: config.ssl === 'mkcert' ? `\n### Configuration SSL (mkcert)\n\nLe script de démarrage génère automatiquement les certificats SSL via mkcert.\n\nSi vous devez le faire manuellement:\n\`\`\`bash\nmkcert -install\ncd certs\nmkcert ${config.domain || 'localhost'}\ncd ..\n\`\`\`\n` : '' }
    };

    const envDoc = envDocs[config.environment] || envDocs['linux-local'];

    md += `**${envDoc.name}**\n\n${envDoc.desc}\n\n`;

    if (envDoc.scriptType === 'powershell') {
      md += `### Démarrage\n\n\`\`\`powershell\n.\\start-containers.ps1\n\`\`\`\n\n`;
      md += `### Arrêt\n\n\`\`\`powershell\n.\\stop-containers.ps1\n\`\`\`\n\n`;
    } else {
      md += `### Démarrage\n\n\`\`\`bash\nchmod +x start-containers.sh\n./start-containers.sh\n\`\`\`\n\n`;
      md += `### Arrêt\n\n\`\`\`bash\nchmod +x stop-containers.sh\n./stop-containers.sh\n\`\`\`\n\n`;
    }

    md += `### Accès\n\n`;
    md += `- Application: ${envDoc.url}\n`;
    if (envDoc.note) md += `- ${envDoc.note}\n`;
    if (envDoc.extraSetup) md += envDoc.extraSetup;
    if (envDoc.sslSetup) md += envDoc.sslSetup;

    md += `\n## Quick start (manuel)\n\n\`\`\`bash\n up -d\n logs -f\n\`\`\`\n`;

    if (config.gitRepoUrl) {
      md += `\n## Initialisation\n\nUn script \`init.sh\` est fourni pour automatiser le setup :\n\n\`\`\`bash\nchmod +x init.sh\n./init.sh\n\`\`\`\n\nCe script va :\n1. Cloner le repository \`${config.gitRepoUrl}\`${config.gitBranch && config.gitBranch !== 'main' ? ` (branche: ${config.gitBranch})` : ''} dans \`src/\`\n2. Demarrer les containers avec \` up -d\`\n3. Installer les dependances du projet\n`;
    }

    if (config.preset === 'wordpress') {
      md += `\n## WordPress setup\n\n1. Download WordPress into \`src/\`:\n   \`\`\`bash\n   curl -O https://wordpress.org/latest.tar.gz\n   tar xzf latest.tar.gz --strip-components=1 -C src/\n   cp src/wp-config.php src/wp-config.php  # already generated\n   \`\`\`\n2. Open http://${config.domain || 'localhost'} and complete the installation.\n`;
    }

    if (config.preset === 'laravel') {
      md += `\n## Laravel setup\n\n\`\`\`bash\n# Create project in src/\n exec php composer create-project laravel/laravel . "${config.laravelVersion || '11'}.*"\n# Copy the generated .env\ncp .env.example src/.env  # then merge with generated values\n exec php php artisan key:generate\n exec php php artisan migrate\n\`\`\`\n`;
    }

    if (config.preset === 'symfony') {
      md += `\n## Symfony setup\n\n\`\`\`bash\n exec php composer create-project symfony/skeleton . "${config.symfonyVersion || '7.2'}.*"\n# Copy .env values from generated file\n exec php php bin/console doctrine:migrations:migrate\n\`\`\`\n`;
    }

    if (config.preset === 'django') {
      md += `\n## Django setup\n\n\`\`\`bash\n# In src/\ndjango-admin startproject config .\npython manage.py migrate\npython manage.py createsuperuser\n\`\`\`\n`;
    }

    if (config.preset === 'springboot') {
      md += `\n## Spring Boot setup\n\nGenerate your project at https://start.spring.io/ or use the provided pom.xml.\n\`\`\`bash\n up -d\n\`\`\`\n`;
    }

    if (config.ssl === 'mkcert') {
      md += `\n## SSL (mkcert)\n\n\`\`\`bash\nmkcert -install\nmkcert -cert-file certs/cert.pem -key-file certs/key.pem ${config.domain || 'localhost'}\n\`\`\`\n`;
    }
    if (config.ssl === 'letsencrypt') {
      md += `\n## SSL (Let's Encrypt)\n\n\`\`\`bash\n run --rm certbot certonly --webroot --webroot-path /var/www/certbot -d ${config.domain || 'example.com'}\n restart nginx\n\`\`\`\n`;
    }

    md += `\n## Access\n\n`;
    const proto = config.ssl !== 'none' ? 'https' : 'http';
    md += `- App: ${proto}://${config.domain || 'localhost'}\n`;
    if (config.adminer) md += `- Adminer: http://localhost:8081\n`;
    if (config.phpmyadmin) md += `- phpMyAdmin: http://localhost:8082\n`;
    if (config.pgadmin) md += `- pgAdmin: http://localhost:8083\n`;
    if (config.mongoexpress) md += `- Mongo Express: http://localhost:8084\n`;
    if (config.mailpit) md += `- Mailpit: http://localhost:8025\n`;
    if (config.minio) md += `- MinIO Console: http://localhost:9001\n`;
    if (config.rabbitmq) md += `- RabbitMQ: http://localhost:15672\n`;
    if (config.webserver === 'traefik') md += `- Traefik: http://localhost:8080\n`;

    return md;
  }
});
